## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# 設定 data_path
dir_data = './data/'

In [3]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ./data/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [10]:
dataRows = app_train.shape[0]
dataColumns = app_train.shape[1]
print(dataRows, dataColumns)

307511 122

#### 列出所有欄位

In [14]:
cols = app_train.columns.values
print(cols)

['SK_ID_CURR' 'TARGET' 'NAME_CONTRACT_TYPE' 'CODE_GENDER' 'FLAG_OWN_CAR'
 'FLAG_OWN_REALTY' 'CNT_CHILDREN' 'AMT_INCOME_TOTAL' 'AMT_CREDIT'
 'AMT_ANNUITY' 'AMT_GOODS_PRICE' 'NAME_TYPE_SUITE' 'NAME_INCOME_TYPE'
 'NAME_EDUCATION_TYPE' 'NAME_FAMILY_STATUS' 'NAME_HOUSING_TYPE'
 'REGION_POPULATION_RELATIVE' 'DAYS_BIRTH' 'DAYS_EMPLOYED'
 'DAYS_REGISTRATION' 'DAYS_ID_PUBLISH' 'OWN_CAR_AGE' 'FLAG_MOBIL'
 'FLAG_EMP_PHONE' 'FLAG_WORK_PHONE' 'FLAG_CONT_MOBILE' 'FLAG_PHONE'
 'FLAG_EMAIL' 'OCCUPATION_TYPE' 'CNT_FAM_MEMBERS' 'REGION_RATING_CLIENT'
 'REGION_RATING_CLIENT_W_CITY' 'WEEKDAY_APPR_PROCESS_START'
 'HOUR_APPR_PROCESS_START' 'REG_REGION_NOT_LIVE_REGION'
 'REG_REGION_NOT_WORK_REGION' 'LIVE_REGION_NOT_WORK_REGION'
 'REG_CITY_NOT_LIVE_CITY' 'REG_CITY_NOT_WORK_CITY'
 'LIVE_CITY_NOT_WORK_CITY' 'ORGANIZATION_TYPE' 'EXT_SOURCE_1'
 'EXT_SOURCE_2' 'EXT_SOURCE_3' 'APARTMENTS_AVG' 'BASEMENTAREA_AVG'
 'YEARS_BEGINEXPLUATATION_AVG' 'YEARS_BUILD_AVG' 'COMMONAREA_AVG'
 'ELEVATORS_AVG' 'ENTRANCES_AVG' 'FLOORSMAX_AVG' 'FLOORSMIN_AVG'
 'LANDAREA_AVG' 'LIVINGAPARTMENTS_AVG' 'LIVINGAREA_AVG'
 'NONLIVINGAPARTMENTS_AVG' 'NONLIVINGAREA_AVG' 'APARTMENTS_MODE'
 'BASEMENTAREA_MODE' 'YEARS_BEGINEXPLUATATION_MODE' 'YEARS_BUILD_MODE'
 'COMMONAREA_MODE' 'ELEVATORS_MODE' 'ENTRANCES_MODE' 'FLOORSMAX_MODE'
 'FLOORSMIN_MODE' 'LANDAREA_MODE' 'LIVINGAPARTMENTS_MODE'
 'LIVINGAREA_MODE' 'NONLIVINGAPARTMENTS_MODE' 'NONLIVINGAREA_MODE'
 'APARTMENTS_MEDI' 'BASEMENTAREA_MEDI' 'YEARS_BEGINEXPLUATATION_MEDI'
 'YEARS_BUILD_MEDI' 'COMMONAREA_MEDI' 'ELEVATORS_MEDI' 'ENTRANCES_MEDI'
 'FLOORSMAX_MEDI' 'FLOORSMIN_MEDI' 'LANDAREA_MEDI' 'LIVINGAPARTMENTS_MEDI'
 'LIVINGAREA_MEDI' 'NONLIVINGAPARTMENTS_MEDI' 'NONLIVINGAREA_MEDI'
 'FONDKAPREMONT_MODE' 'HOUSETYPE_MODE' 'TOTALAREA_MODE'
 'WALLSMATERIAL_MODE' 'EMERGENCYSTATE_MODE' 'OBS_30_CNT_SOCIAL_CIRCLE'
 'DEF_30_CNT_SOCIAL_CIRCLE' 'OBS_60_CNT_SOCIAL_CIRCLE'
 'DEF_60_CNT_SOCIAL_CIRCLE' 'DAYS_LAST_PHONE_CHANGE' 'FLAG_DOCUMENT_2'
 'FLAG_DOCUMENT_3' 'FLAG_DOCUMENT_4' 'FLAG_DOCUMENT_5' 'FLAG_DOCUMENT_6'
 'FLAG_DOCUMENT_7' 'FLAG_DOCUMENT_8' 'FLAG_DOCUMENT_9' 'FLAG_DOCUMENT_10'
 'FLAG_DOCUMENT_11' 'FLAG_DOCUMENT_12' 'FLAG_DOCUMENT_13'
 'FLAG_DOCUMENT_14' 'FLAG_DOCUMENT_15' 'FLAG_DOCUMENT_16'
 'FLAG_DOCUMENT_17' 'FLAG_DOCUMENT_18' 'FLAG_DOCUMENT_19'
 'FLAG_DOCUMENT_20' 'FLAG_DOCUMENT_21' 'AMT_REQ_CREDIT_BUREAU_HOUR'
 'AMT_REQ_CREDIT_BUREAU_DAY' 'AMT_REQ_CREDIT_BUREAU_WEEK'
 'AMT_REQ_CREDIT_BUREAU_MON' 'AMT_REQ_CREDIT_BUREAU_QRT'
 'AMT_REQ_CREDIT_BUREAU_YEAR']

#### 截取部分資料

In [21]:
contractType = app_train["NAME_CONTRACT_TYPE"] == "Cash loans"
gender =  app_train["CODE_GENDER"] == "M"
amtIncomeTotal = app_train["AMT_INCOME_TOTAL"] >= 1000000
app_train[(contractType & gender & amtIncomeTotal)]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
1504,101769,0,Cash loans,M,Y,Y,0,1080000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
1723,102015,0,Cash loans,M,N,Y,0,1935000.0,269550.0,10534.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3371,103938,0,Cash loans,M,N,N,1,1350000.0,2410380.0,109053.0,...,1,0,0,0,0.0,0.0,0.0,3.0,0.0,0.0
4603,105384,0,Cash loans,M,Y,Y,0,1350000.0,405000.0,20250.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
7061,108224,0,Cash loans,M,Y,N,0,1035000.0,2695500.0,74254.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
8314,109690,0,Cash loans,M,N,Y,0,1350000.0,427450.5,18238.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
10222,111903,0,Cash loans,M,N,Y,3,2250000.0,900000.0,45000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
11068,112894,0,Cash loans,M,Y,N,0,1350000.0,835380.0,40189.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
11344,113213,0,Cash loans,M,Y,N,0,1125000.0,701730.0,72036.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
12005,114000,0,Cash loans,M,Y,Y,0,1125000.0,848308.5,63427.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
12108,114122,0,Cash loans,M,Y,Y,0,1080000.0,2250000.0,225000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
12840,114967,1,Cash loans,M,N,Y,1,117000000.0,562491.0,26194.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
14048,116374,0,Cash loans,M,N,N,0,1125000.0,936000.0,30325.5,...,0,0,0,0,0.0,0.0,0.0,0.0,3.0,1.0
16998,119830,0,Cash loans,M,Y,N,0,1125000.0,675000.0,33750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
17721,120659,0,Cash loans,M,Y,Y,2,1800000.0,1125000.0,36423.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,3.0
19665,122933,0,Cash loans,M,Y,Y,0,1350000.0,1030680.0,65866.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
19995,123321,0,Cash loans,M,N,Y,1,1125000.0,360000.0,17509.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,0.0
20216,123587,0,Cash loans,M,Y,N,0,3825000.0,1241023.5,117369.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,0.0
22897,126644,0,Cash loans,M,Y,Y,0,1125000.0,2013840.0,53253.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
23975,127883,0,Cash loans,M,Y,N,0,1800000.0,1350000.0,67500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
24531,128538,0,Cash loans,M,Y,Y,0,1350000.0,585000.0,29250.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
24741,128777,0,Cash loans,M,Y,Y,0,1282500.0,1095111.0,58477.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
25626,129799,0,Cash loans,M,Y,N,2,1350000.0,675000.0,33750.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,3.0
29286,134013,0,Cash loans,M,N,N,0,1350000.0,305221.5,15633.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
29647,134422,0,Cash loans,M,Y,Y,0,1125000.0,1379376.0,40459.5,...,0,0,0,0,0.0,0.0,0.0,4.0,1.0,1.0
29737,134526,0,Cash loans,M,N,N,0,2250000.0,1350000.0,67500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
30514,135417,0,Cash loans,M,Y,N,0,1080000.0,675000.0,33750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
32771,137980,0,Cash loans,M,Y,Y,1,1125000.0,1024740.0,52452.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
33485,138790,0,Cash loans,M,Y,Y,3,1125000.0,640080.0,31261.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
35572,141198,0,Cash loans,M,Y,Y,1,2025000.0,733315.5,41076.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268444,411086,0,Cash loans,M,N,N,1,1417500.0,254700.0,16276.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
268769,411466,0,Cash loans,M,Y,N,1,1575000.0,1499688.0,79281.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
269915,412823,0,Cash loans,M,Y,N,0,1035000.0,1984500.0,62937.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
270558,413588,0,Cash loans,M,Y,Y,0,1125000.0,1298655.0,34389.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
275313,419053,0,Cash loans,M,Y,Y,0,1306831.5,157500.0,7875.0,...,1,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
278212,422344,0,Cash loans,M,Y,Y,0,2250000.0,1506816.0,49927.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
280170,424585,0,Cash loans,M,Y,Y,1,1260000.0,1125000.0,109728.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
280568,425042,0,Cash loans,M,N,N,0,1575000.0,508495.5,21672.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
282771,427512,0,Cash loans,M,Y,Y,0,1125000.0,953460.0,63976.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
284311,429258,0,Cash loans,M,Y,N,0,3600000.0,1113840.0,44302.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
285888,431111,0,Cash loans,M,Y,Y,1,1800000.0,849685.5,33196.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
286982,432396,0,Cash loans,M,Y,Y,0,1260000.0,1288350.0,37800.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,5.0
287307,432802,0,Cash loans,M,Y,Y,0,1001826.0,1800000.0,73314.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
287463,432980,0,Cash loans,M,Y,Y,0,4500000.0,1755000.0,61132.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0
293055,439504,0,Cash loans,M,Y,Y,0,1125000.0,1325475.0,54832.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0
293148,439616,0,Cash loans,M,Y,Y,0,1350000.0,277969.5,18094.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
293342,439846,0,Cash loans,M,Y,Y,0,1575000.0,2031651.0,188136.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
294076,440695,0,Cash loans,M,Y,Y,2,2025000.0,808650.0,26217.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
294141,440768,0,Cash loans,M,N,Y,0,1800000.0,900000.0,45000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
294383,441052,0,Cash loans,M,Y,Y,1,1350000.0,1350000.0,67500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
294589,441287,0,Cash loans,M,Y,N,0,1350000.0,450000.0,21109.5,...,0,0,0,0,0.0,0.0,0.0,1.0,2.0,5.0
294892,441639,0,Cash loans,M,N,Y,0,2250000.0,675000.0,33750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
296216,443181,0,Cash loans,M,Y,Y,1,1125000.0,1218555.0,84937.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,4.0
296626,443665,0,Cash loans,M,N,N,0,1125000.0,2007000.0,53073.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
297755,444955,0,Cash loans,M,N,Y,0,1035000.0,1575000.0,54877.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
298082,445335,0,Cash loans,M,Y,Y,0,2475000.0,1125000.0,47794.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
300468,448102,0,Cash loans,M,N,Y,0,1575000.0,1223010.0,51948.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
304477,452764,0,Cash loans,M,Y,Y,1,2025000.0,935640.0,93487.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
305577,454039,0,Cash loans,M,Y,Y,0,1215000.0,1264738.5,67513.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,3.0
306028,454569,0,Cash loans,M,Y,Y,0,1350000.0,1575000.0,78750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子